[package]
name = "yewi-kit"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.22.0", features = ["csr", "serde"] }
wasm-logger = "0.2.0"
yew-router = "0.19.0"
web-sys = { version = "0.3.83", features = ["DataTransfer"] }
uuid = {  version = "1.19.0", features = ["v4", "js"] }