[serve]
address = "127.0.0.1"
port = 8081

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
    "-c", "sass ./src/styles/main.scss ./dist/main.css && npx tailwindcss -i ./dist/main.css -o ./src/styles/global.css --minify"
]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c", "cp -r ./_routes.json ./dist/_routes.json"
]

[watch]
ignore = ["src/styles/global.css"]