[serve]
address = "127.0.0.1"
port = 8081

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = [
    "run", "build"
]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c", "cp -r ./_routes.json ./dist/_routes.json"
]

[watch]
ignore = ["src/styles/global.css"]